using CashRegister.Core;
using Server.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Xunit;

namespace CashRegister.Test
{
    public class ApiReceiptDtoTests
    {
        private readonly HttpClient _client;

        public ApiReceiptDtoTests()
        {
            _client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:5001/")
            };
        }

        [Fact]
        public async Task BuildReceipt_FromApiData_ShouldBeValid()
        {
            var products = await _client.GetFromJsonAsync<List<Product>>("api/products");
            var promotions = await _client.GetFromJsonAsync<List<Promotion>>("api/promotions");

            Assert.NotNull(products);
            Assert.NotNull(promotions);

            var rand = new Random();
            var selected = products.OrderBy(_ => rand.Next()).Take(3).ToList();

            var lines = selected.Select(p => new ReceiptLine
            {
                Name = p.Name,
                Upc = p.Upc,
                Quantity = rand.Next(1, 4),
                UnitPrice = p.Price,
                Discount = 0m
            }).ToList();

            PricingEngine.ApplyPromotions(lines, promotions);

            var total = ReceiptCalculator.CalculateTotal(lines);
            var vatLines = ReceiptCalculator.ComputeVatLines(lines, selected);

            var receipt = new Receipt
            {
                ReceiptNumber = rand.Next(100000, 999999).ToString(),
                Timestamp = DateTime.Now,
                DocumentType = "Receipt",
                KvitasNumber = rand.Next(100000, 999999),
                PosId = 1,
                Items = lines,
                Payments = new List<Payment> { new Payment { Method = "Card", Amount = total } },
                Change = 0m,
                VatLines = vatLines,
                RawText = "Test receipt generated by unit test"
            };

            // Assertions
            Assert.NotNull(receipt);
            Assert.Equal(3, receipt.Items.Count);
            Assert.Single(receipt.Payments);
            Assert.True(receipt.Payments[0].Amount >= 0);
            Assert.True(receipt.VatLines.Count > 0);
            Assert.Equal("Receipt", receipt.DocumentType);

            // Output for human-readable verification
            Console.WriteLine($"Receipt #{receipt.ReceiptNumber} @ {receipt.Timestamp}");
            foreach (var item in receipt.Items)
            {
                Console.WriteLine($"{item.Quantity} x {item.Name} @ {item.UnitPrice:C} - Discount: {item.Discount:C}");
            }
            Console.WriteLine($"Total Paid: {receipt.Payments[0].Amount:C}, Change: {receipt.Change:C}");
            foreach (var vat in receipt.VatLines)
            {
                Console.WriteLine($"VAT {vat.Rate}% - Base: {vat.Base:C}, Amount: {vat.Amount:C}, Total: {vat.Total:C}");
            }
        }
    }
}

